---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)

df <- read_csv('data/emergency.csv')

df <- df %>% mutate(infection = factor(infection,
                                        levels = 0:1,
                                        labels = c("No", "Yes")),
                               gender = 
                                 factor(gender,
                                        levels = 0:1,
                                        labels = c("Female", "Male")),
                               child =
                                 factor(child,
                                        levels = 0:2,
                                        labels = c("A", "B", "C")),
                               encephalopathy =
                                 factor(encephalopathy,
                                        levels = 0:1,
                                        labels = c("No", "Yes")),
                               ascites =
                                 factor(ascites,
                                        levels = 0:1,
                                        labels = c("No", "Yes")),
                               death = 
                                 factor(death,
                                        levels = 0:1,
                                        labels = c("No", "Yes")))

```

```{r}
ggplot(df, aes(x = gender, y = los, fill = gender)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', method = 'histodot', binwidth = 3) +
  stat_summary(fun.y = median, fun.ymax = median, fun.ymin = median, geom = 'crossbar', width = .5, color = 'red') +
  scale_y_continuous(breaks = seq(0,100,10)) +
  facet_grid(infection ~ death, labeller = label_both) +
  theme_bw() +
  theme(legend.position = 'none',
        panel.grid = element_blank(),
        axis.title = element_text(face = 'bold')) +
  labs(x = 'Gender', y = 'Length of Stay (Days)', title = str_to_title('Length of Stay between Male and Female'), subtitle = str_to_title('stratified by Infection and Mortality'), caption = 'Crossbar represents median LOS for respective groups') +
  scale_x_discrete(labels = c('0' = 'Female', '1' = 'Male'))
```

```{r}
ggplot(df, aes(x = gender, y = hr, fill = gender)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', method = 'histodot', binwidth = 3) +
  stat_summary(fun.y = median, fun.ymax = median, fun.ymin = median, geom = 'crossbar', width = .5, color = 'red') +
  scale_y_continuous(breaks = seq(0,300,20)) +
  facet_grid(infection ~ death + encephalopathy, labeller = label_both) +
  theme_bw() +
  theme(legend.position = 'none',
        panel.grid = element_blank(),
        axis.title = element_text(face = 'bold')) +
  labs(x = 'Gender', y = 'Heart Rate (beats / min)', title = str_to_title('Heart Rate between Male and Female'), subtitle = str_to_title('stratified by Infection and Mortality and encephalopathy'), caption = 'Crossbar represents median heart rate for respective groups')
```

